<?php

use Illuminate\Database\Seeder;

class DirectorioExternoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Gema Alejandrina ',
    		'apellido1' => 'Mercado',
    		'apellido2' => 'Sánchez',
    		'nombre_c' => 'Gema Alejandrina  Mercado Sánchez',
    		'a_n' => 'GAMS',
    		'lic' => 'Dra',
    		'puesto' => 'Secretaria de Educación',
    		'direccion' => ' Secretaria de Educacion ',
    		'a_d' => 'SE',
    		'correo' => 'gmercado@seduzac.gob.mx',
    		'ext' => '5010',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Mario Alberto ',
    		'apellido1' => 'Ramírez',
    		'apellido2' => 'Rodríguez',
    		'nombre_c' => 'Mario Alberto  Ramírez Rodríguez',
    		'a_n' => 'MARR',
    		'lic' => '',
    		'puesto' => 'Coordinador Tecnico',
    		'direccion' => ' Coordinación Tecnica ',
    		'a_d' => 'CT',
    		'correo' => 'coor-tecnico@seduzac.gob.mx',
    		'ext' => '5020',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Jaime',
    		'apellido1' => 'Arteaga',
    		'apellido2' => 'Hernández',
    		'nombre_c' => 'Jaime Arteaga Hernández',
    		'a_n' => 'JAH',
    		'lic' => '',
    		'puesto' => 'Coordinador de Direcciones Regionales ',
    		'direccion' => ' Coordinación de Direcciones Regionales ',
    		'a_d' => 'CDR',
    		'correo' => 'codrese@hotmail.com',
    		'ext' => '5820',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Luis Noé',
    		'apellido1' => 'Maldonado',
    		'apellido2' => 'Sánchez',
    		'nombre_c' => 'Luis Noé Maldonado Sánchez',
    		'a_n' => 'LNMS',
    		'lic' => '',
    		'puesto' => 'Titular del Órgano Interno de Control',
    		'direccion' => ' Órgano Interno de Control ',
    		'a_d' => 'OIC',
    		'correo' => 'oic@seduzac.gob.mx',
    		'ext' => '5009',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Salvador ',
    		'apellido1' => 'Salman',
    		'apellido2' => 'Tagle',
    		'nombre_c' => 'Salvador  Salman Tagle',
    		'a_n' => 'SST',
    		'lic' => '',
    		'puesto' => 'Titular de la Unidad de Transparencia',
    		'direccion' => ' Unidad de Transparencia ',
    		'a_d' => 'UT',
    		'correo' => 'unidadenlace@seduzac.gob.mx',
    		'ext' => '5054',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan Carlos',
    		'apellido1' => 'Flores',
    		'apellido2' => 'Solis',
    		'nombre_c' => 'Juan Carlos Flores Solis',
    		'a_n' => 'JCFS',
    		'lic' => '',
    		'puesto' => 'Director Jurídico',
    		'direccion' => ' Direccion Juridica ',
    		'a_d' => 'DJ',
    		'correo' => 'jcflores@seduzac.gob.mx',
    		'ext' => '5060',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Rigoberto',
    		'apellido1' => 'Robles ',
    		'apellido2' => 'Castillo',
    		'nombre_c' => 'Rigoberto Robles  Castillo',
    		'a_n' => 'RRC',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Asuntos Jurídicos Administrativos',
    		'direccion' => ' Departamento de Asuntos Jurídicos Administrativos ',
    		'a_d' => 'DAJA',
    		'correo' => 'dajaeducacion@outloock.com',
    		'ext' => '5060',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Antonia ',
    		'apellido1' => 'Cruz ',
    		'apellido2' => 'Pacheco',
    		'nombre_c' => 'Antonia  Cruz  Pacheco',
    		'a_n' => 'ACP',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Asuntos Jurisdiccionales ',
    		'direccion' => ' Departamento de Asuntos Jurisdiccionales  ',
    		'a_d' => 'DAJ',
    		'correo' => 'jcflores@seduzac.gob.mx',
    		'ext' => '5062',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juana Maria Luciana',
    		'apellido1' => 'Castrellón ',
    		'apellido2' => 'Acosta',
    		'nombre_c' => 'Juana Maria Luciana Castrellón  Acosta',
    		'a_n' => 'JMLCA',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Atención Legal Adjunta',
    		'direccion' => ' Departamento de Atención Legal Adjunta ',
    		'a_d' => 'DELA',
    		'correo' => 'inmueblesseduzac@gmail.com',
    		'ext' => '5063',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Daniel',
    		'apellido1' => 'Rodríguez',
    		'apellido2' => 'Lemus',
    		'nombre_c' => 'Daniel Rodríguez Lemus',
    		'a_n' => 'DRL',
    		'lic' => 'Mtro',
    		'puesto' => 'Subsecretario Académico',
    		'direccion' => ' Subsecretaria Academica ',
    		'a_d' => 'SA',
    		'correo' => 'honorio.jimenez@seduzac.gob.mx',
    		'ext' => '5310',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Guillermo',
    		'apellido1' => 'Guerra',
    		'apellido2' => 'Mireles',
    		'nombre_c' => 'Guillermo Guerra Mireles',
    		'a_n' => 'GGM',
    		'lic' => '',
    		'puesto' => 'Secretario Técnico',
    		'direccion' => ' Secretaria Tecnica ',
    		'a_d' => 'ST',
    		'correo' => 'honorio.jimenez@seduzac.gob.mx',
    		'ext' => '5310',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Maria Dolores',
    		'apellido1' => 'Sandoval ',
    		'apellido2' => 'Ordaz',
    		'nombre_c' => 'Maria Dolores Sandoval  Ordaz',
    		'a_n' => 'MDSO',
    		'lic' => '',
    		'puesto' => 'Directora General de Fortalecimiento Docente',
    		'direccion' => ' Dirección General de Fortalecimiento Docente ',
    		'a_d' => 'DGFD',
    		'correo' => 'dgfdocente@seduzac.gob.mx',
    		'ext' => '5350',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Milda del Consuelo',
    		'apellido1' => 'Galván',
    		'apellido2' => 'Coral',
    		'nombre_c' => 'Milda del Consuelo Galván Coral',
    		'a_n' => 'MCGC',
    		'lic' => '',
    		'puesto' => 'Directora del Servicio Profesional Docente',
    		'direccion' => ' Dirección del  Servicio Profesional Docente ',
    		'a_d' => 'DSPD',
    		'correo' => 'dspdocente@seduzac.gob.mx',
    		'ext' => '5900',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Rocio',
    		'apellido1' => 'Rosas ',
    		'apellido2' => 'Jaso',
    		'nombre_c' => 'Rocio Rosas  Jaso',
    		'a_n' => 'RRJ',
    		'lic' => '',
    		'puesto' => 'Directora de Fortalecimiento Educativo',
    		'direccion' => ' Dirección de Fortalecimiento Educativo ',
    		'a_d' => 'DFE',
    		'correo' => 'dseducativo@seduzac.gob.mx',
    		'ext' => '5354',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'vacante',
    		'apellido1' => 'vacante',
    		'apellido2' => 'vacante',
    		'nombre_c' => 'vacante vacante vacante',
    		'a_n' => '',
    		'lic' => '',
    		'puesto' => 'Instituto Superior de Desarrollo Profesional Docente de Zacatecas',
    		'direccion' => ' ',
    		'a_d' => 'ISDPD',
    		'correo' => 'isdpdocentezac@seduzac.gob.mx',
    		'ext' => '9220878',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan Carlos',
    		'apellido1' => 'Lozano',
    		'apellido2' => 'Martínez',
    		'nombre_c' => 'Juan Carlos Lozano Martínez',
    		'a_n' => 'JCLM',
    		'lic' => '',
    		'puesto' => 'Director de Fortalecimiento Estudiantil',
    		'direccion' => ' Dirección de Fortalecimiento Estudiantil ',
    		'a_d' => 'DFE',
    		'correo' => 'dfestudiantil@seduzac.gob.mx',
    		'ext' => '5180',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Olivia Margarita ',
    		'apellido1' => 'Saucedo ',
    		'apellido2' => 'Encina',
    		'nombre_c' => 'Olivia Margarita  Saucedo  Encina',
    		'a_n' => 'OMSE',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Ambiente Escolar',
    		'direccion' => ' Departamento de Ambiente Escolar ',
    		'a_d' => 'DAE',
    		'correo' => 'aescolares.seczac@hotmail.com',
    		'ext' => '5220',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Jesús ',
    		'apellido1' => 'Castañeda',
    		'apellido2' => 'Delgado',
    		'nombre_c' => 'Jesús  Castañeda Delgado',
    		'a_n' => 'JCD',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Becas',
    		'direccion' => ' Departamento de Becas ',
    		'a_d' => 'DB',
    		'correo' => 'depto.becas@seduzac.gob.mx',
    		'ext' => '5190',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'José Luis',
    		'apellido1' => 'Huitrado',
    		'apellido2' => 'Rizo',
    		'nombre_c' => 'José Luis Huitrado Rizo',
    		'a_n' => 'JLHR',
    		'lic' => 'Mtro',
    		'puesto' => 'Director de Fortalecimiento Escolar',
    		'direccion' => ' Dirección de Fortalecimiento Escolar ',
    		'a_d' => 'DFE',
    		'correo' => 'dfescolar@seduzac.gob.mx',
    		'ext' => '5314',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Alba Citlalli',
    		'apellido1' => 'Córdova',
    		'apellido2' => 'Rojas',
    		'nombre_c' => 'Alba Citlalli Córdova Rojas',
    		'a_n' => 'ACCR',
    		'lic' => 'Dra',
    		'puesto' => 'Jefa del Departamento de Horario Ampliado',
    		'direccion' => ' Departamento de Horario Ampliado ',
    		'a_d' => 'DHA',
    		'correo' => 'dfescolar@seduzac.gob.mx',
    		'ext' => '5314',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'María de Jesús ',
    		'apellido1' => 'Valdívia ',
    		'apellido2' => 'Esquivel',
    		'nombre_c' => 'María de Jesús  Valdívia  Esquivel',
    		'a_n' => 'MJVE',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Programas de Desarrollo Escolar',
    		'direccion' => ' Departamento de Programas de Desarrollo Escolar ',
    		'a_d' => 'DPDE',
    		'correo' => 'dfescolar@seduzac.gob.mx',
    		'ext' => '5314',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Luis Hugo ',
    		'apellido1' => 'Nuñez ',
    		'apellido2' => 'Bermudez',
    		'nombre_c' => 'Luis Hugo  Nuñez  Bermudez',
    		'a_n' => 'LHNB',
    		'lic' => '',
    		'puesto' => 'Coordinador Estatal de Bibliotecas',
    		'direccion' => ' Coordinacion Estatal de Bibliotecas ',
    		'a_d' => 'CEB',
    		'correo' => 'coord.estatalbiblio@seduzac.gob.mx',
    		'ext' => '9240562',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan  Carlos',
    		'apellido1' => 'Ochoa ',
    		'apellido2' => 'Valenzuela',
    		'nombre_c' => 'Juan  Carlos Ochoa  Valenzuela',
    		'a_n' => 'JCOV',
    		'lic' => '',
    		'puesto' => 'Coordinador Regional de Bibliotecas',
    		'direccion' => ' Coordinación Regional de Bibliotecas ',
    		'a_d' => 'CRB',
    		'correo' => 'coord.regionalbiblio@seduzac.gob.mx',
    		'ext' => '9255370',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Victor Hugo ',
    		'apellido1' => 'García ',
    		'apellido2' => 'Sandoval',
    		'nombre_c' => 'Victor Hugo  García  Sandoval',
    		'a_n' => 'VHGS',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Promoción Cultural',
    		'direccion' => ' Departamento de Promoción Cultural ',
    		'a_d' => 'DPC',
    		'correo' => 'deptopromocultural@seduzac.gob.mx',
    		'ext' => '9240562',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'José Manuel ',
    		'apellido1' => 'Maldonado',
    		'apellido2' => 'Romero',
    		'nombre_c' => 'José Manuel  Maldonado Romero',
    		'a_n' => 'JMMR',
    		'lic' => '',
    		'puesto' => 'Subsecretario de Educacion Básica',
    		'direccion' => ' Subsecretaria de Educación Basica ',
    		'a_d' => 'SEB',
    		'correo' => 'subsebn@seduzac.gob.mx',
    		'ext' => '5300',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Herminia',
    		'apellido1' => 'Hernández',
    		'apellido2' => 'Castro',
    		'nombre_c' => 'Herminia Hernández Castro',
    		'a_n' => 'HHC',
    		'lic' => '',
    		'puesto' => 'Secretaria Tecnica',
    		'direccion' => ' Secretaria Tecnica ',
    		'a_d' => 'ST',
    		'correo' => 'subsebn@seduzac.gob.mx',
    		'ext' => '5300',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Huberto',
    		'apellido1' => 'Meléndez',
    		'apellido2' => 'Martínez',
    		'nombre_c' => 'Huberto Meléndez Martínez',
    		'a_n' => 'HMM',
    		'lic' => '',
    		'puesto' => 'Director de Educación Básica Federalizada',
    		'direccion' => ' Dirección de Educación Básica Federalizada ',
    		'a_d' => 'DEBF',
    		'correo' => 'hmelendez@seduzac.gob.mx',
    		'ext' => '5380',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Imelda ',
    		'apellido1' => 'Villegas',
    		'apellido2' => 'Santillan',
    		'nombre_c' => 'Imelda  Villegas Santillan',
    		'a_n' => 'IVS',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Educacion Inicial y Preescolar',
    		'direccion' => ' Departamento de Educacion Inicial y Preescolar ',
    		'a_d' => 'DEIP',
    		'correo' => 'imvisa@seduzac.gob.mx',
    		'ext' => '5392',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'J. Jesús',
    		'apellido1' => 'Esparza',
    		'apellido2' => 'Yañez',
    		'nombre_c' => 'J. Jesús Esparza Yañez',
    		'a_n' => 'JJEY',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Educación Primaria',
    		'direccion' => ' Departamento de Educación Primaria ',
    		'a_d' => 'DEP',
    		'correo' => 'primariasfederaleszac@gmail.com',
    		'ext' => '5400',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Belarmina ',
    		'apellido1' => 'García ',
    		'apellido2' => 'Castro',
    		'nombre_c' => 'Belarmina  García  Castro',
    		'a_n' => 'BGC',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Educación Secundaria General',
    		'direccion' => ' Departamento de Educación Secundaria General ',
    		'a_d' => 'DESG',
    		'correo' => 'oficina_sec_fed@hotmail.com',
    		'ext' => '5440',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Daniel',
    		'apellido1' => 'Solis',
    		'apellido2' => 'Ibarra',
    		'nombre_c' => 'Daniel Solis Ibarra',
    		'a_n' => 'DSI',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Educación Secundaria Técnica',
    		'direccion' => ' Departamento de Educación Secundaria Técnica ',
    		'a_d' => 'DEST',
    		'correo' => 'secundariastecnicasfed@gmail.com',
    		'ext' => '5415',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Martín Javier ',
    		'apellido1' => 'Hernández ',
    		'apellido2' => 'Dones',
    		'nombre_c' => 'Martín Javier  Hernández  Dones',
    		'a_n' => 'MJHD',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Educación Especial',
    		'direccion' => ' Departamento de Educación Especial ',
    		'a_d' => 'DEE',
    		'correo' => 'edespfed@mail.seduzac.gob.mx',
    		'ext' => '5420',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Dra. Aida Liliana',
    		'apellido1' => 'Solano',
    		'apellido2' => 'García',
    		'nombre_c' => 'Dra. Aida Liliana Solano García',
    		'a_n' => 'DALSG',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Educación Física',
    		'direccion' => ' Departamento de Educación Física ',
    		'a_d' => 'DEF',
    		'correo' => 'zacatecascondeba@yahoo.com.mx',
    		'ext' => '5430',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Adrián ',
    		'apellido1' => 'Carrillo',
    		'apellido2' => 'Vázquez',
    		'nombre_c' => 'Adrián  Carrillo Vázquez',
    		'a_n' => 'ACV',
    		'lic' => '',
    		'puesto' => 'Director de Educación Basica Estatal',
    		'direccion' => ' Dirección de Educación Basica Estatal ',
    		'a_d' => 'DEBE',
    		'correo' => 'debez@seduzac.gob.mx',
    		'ext' => '5450',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Sonia Elizabeth',
    		'apellido1' => 'Reyes',
    		'apellido2' => 'Ortiz',
    		'nombre_c' => 'Sonia Elizabeth Reyes Ortiz',
    		'a_n' => 'SERO',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Educación Inicial y Preescolar',
    		'direccion' => ' Departamento de Educación Inicial y Preescolar ',
    		'a_d' => 'DEIP',
    		'correo' => 'preescest@mail.seduzac.gob.mx',
    		'ext' => '5460',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Vacante',
    		'apellido1' => 'vacante',
    		'apellido2' => 'vacante',
    		'nombre_c' => 'Vacante vacante vacante',
    		'a_n' => 'V',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Educación Primaria',
    		'direccion' => ' Departamento de Educación Primaria ',
    		'a_d' => 'DEP',
    		'correo' => 'debez@seduzac.gob.mx',
    		'ext' => '5470',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Yair',
    		'apellido1' => 'Plancarte',
    		'apellido2' => 'Martinez',
    		'nombre_c' => 'Yair Plancarte Martinez',
    		'a_n' => 'YPM',
    		'lic' => '',
    		'puesto' => 'Encargado del Departamento de Educación Secundaria ',
    		'direccion' => ' Departamento de Educación Secundaria  ',
    		'a_d' => 'DES',
    		'correo' => 'yirplancarte@hotmail.com',
    		'ext' => '5509',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Rosana ',
    		'apellido1' => 'Vargas ',
    		'apellido2' => 'Díaz',
    		'nombre_c' => 'Rosana  Vargas  Díaz',
    		'a_n' => 'RVD',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Educación Física',
    		'direccion' => ' Departamento de Educación Física ',
    		'a_d' => 'DEF',
    		'correo' => 'edfisest@mail.seduzac.gob.mx',
    		'ext' => '5490',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'David Eduardo ',
    		'apellido1' => 'Rivera ',
    		'apellido2' => 'Salinas',
    		'nombre_c' => 'David Eduardo  Rivera  Salinas',
    		'a_n' => 'DERS',
    		'lic' => '',
    		'puesto' => 'Subsecretario de Educación Media y Superior',
    		'direccion' => ' Subsecretaria de Educación Media y Superior ',
    		'a_d' => 'SEMS',
    		'correo' => 'derivera@seduzac.gob.mx',
    		'ext' => '5759',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Bertha',
    		'apellido1' => 'Carrillo',
    		'apellido2' => 'Fletes',
    		'nombre_c' => 'Bertha Carrillo Fletes',
    		'a_n' => 'BCF',
    		'lic' => '',
    		'puesto' => 'Secretaria Técnica',
    		'direccion' => ' Secretaria Tecnica ',
    		'a_d' => 'ST',
    		'correo' => 'nayzac27@yahoo.com.mx',
    		'ext' => '5752',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Victor Octavio',
    		'apellido1' => 'Espinoza',
    		'apellido2' => 'Lozano',
    		'nombre_c' => 'Victor Octavio Espinoza Lozano',
    		'a_n' => 'VOEL',
    		'lic' => '',
    		'puesto' => 'Director de Educación Media',
    		'direccion' => ' Dirección de Educación Media ',
    		'a_d' => 'DEM',
    		'correo' => 'mediasuperior@seduzac.gob.mx',
    		'ext' => '5800',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Vacante',
    		'apellido1' => 'vacante',
    		'apellido2' => 'vacante',
    		'nombre_c' => 'Vacante vacante vacante',
    		'a_n' => 'V',
    		'lic' => '',
    		'puesto' => 'Coordinador de Organismos Públicos Descentralizados e Incorporados',
    		'direccion' => ' Coordinación de Organismos Públicos Descentralizados e Incorporados ',
    		'a_d' => 'COPDI',
    		'correo' => 'mediasuperior@seduzac.gob.mx',
    		'ext' => '5800',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Omar Gilberto',
    		'apellido1' => 'Martínez ',
    		'apellido2' => 'Carlos',
    		'nombre_c' => 'Omar Gilberto Martínez  Carlos',
    		'a_n' => 'OGMC',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Preparatorias Estatales',
    		'direccion' => '  Departamento de Preparatorias Estatales ',
    		'a_d' => 'DPE',
    		'correo' => 'depto_preparatorias_estatales@seduzac.gob.mx ',
    		'ext' => '5769',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Adrian',
    		'apellido1' => 'Sánchez ',
    		'apellido2' => 'Dueñas',
    		'nombre_c' => 'Adrian Sánchez  Dueñas',
    		'a_n' => 'ASD',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Preparatoria Abierta y en Línea',
    		'direccion' => ' Departamento de Preparatoria Abierta y en Línea ',
    		'a_d' => 'DPA',
    		'correo' => 'prepa_abierta_zac@hotmail.com',
    		'ext' => '9254090',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ivonne Monserrat',
    		'apellido1' => 'Rodriguez',
    		'apellido2' => 'Martínez',
    		'nombre_c' => 'Ivonne Monserrat Rodriguez Martínez',
    		'a_n' => 'IMRM',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Telebachillerato Comunitario',
    		'direccion' => ' Departamento de Telebachillerato Comunitario ',
    		'a_d' => 'DTC',
    		'correo' => 'telebachilleratozac@hotmail.com',
    		'ext' => '5755',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Adriana',
    		'apellido1' => 'Aleman',
    		'apellido2' => 'Olague',
    		'nombre_c' => 'Adriana Aleman Olague',
    		'a_n' => 'AAO',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Centros de Capacitación para el Trabajo',
    		'direccion' => ' Departamento de Centros de Capacitación para el Trabajo ',
    		'a_d' => 'DCCT',
    		'correo' => 'adaleman@yahoo.com.mx',
    		'ext' => '5756',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'José de Jesús ',
    		'apellido1' => 'Reveles',
    		'apellido2' => 'Márquez',
    		'nombre_c' => 'José de Jesús  Reveles Márquez',
    		'a_n' => 'JJRM',
    		'lic' => '',
    		'puesto' => 'Director de Educación Superior',
    		'direccion' => ' Dirección de Educación Superior ',
    		'a_d' => 'DES',
    		'correo' => 'educacionsuperior@seduzac.gob.mx',
    		'ext' => '5789',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Vacante',
    		'apellido1' => 'Vacante',
    		'apellido2' => 'Vacante',
    		'nombre_c' => 'Vacante Vacante Vacante',
    		'a_n' => 'VVV',
    		'lic' => '',
    		'puesto' => 'Coordinador de Organismos Públicos Descentralizados y Estatales',
    		'direccion' => ' Coordinación de Organismos Públicos Descentralizados y Estatales ',
    		'a_d' => 'COPDE',
    		'correo' => 'educacionsuperior@seduzac.gob.mx',
    		'ext' => '5780',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Hilda Cristina',
    		'apellido1' => 'Maldonado',
    		'apellido2' => 'López',
    		'nombre_c' => 'Hilda Cristina Maldonado López',
    		'a_n' => 'HCML',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Escuelas Normales',
    		'direccion' => ' Departamento de Escuelas Normales ',
    		'a_d' => 'DEN',
    		'correo' => 'cristina.maldonado@seduzac.gob.mx',
    		'ext' => '5340',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Eréndira Mariela',
    		'apellido1' => 'Zúñiga',
    		'apellido2' => 'Hernández',
    		'nombre_c' => 'Eréndira Mariela Zúñiga Hernández',
    		'a_n' => 'EMZH',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Instituciones Particulares ',
    		'direccion' => ' Departamento de Instituciones Particulares  ',
    		'a_d' => 'DIP',
    		'correo' => 'educacionsuperior@seduzac.gob.mx',
    		'ext' => '5810',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Martha Imelda',
    		'apellido1' => 'Rangel',
    		'apellido2' => 'Trujillo',
    		'nombre_c' => 'Martha Imelda Rangel Trujillo',
    		'a_n' => 'MIRT',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Certificaciones',
    		'direccion' => ' Departamento de Certificaciones ',
    		'a_d' => 'DC ',
    		'correo' => 'mrangel_profesiones@hotmail.com',
    		'ext' => '5149',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Perla Inés',
    		'apellido1' => 'Velasco',
    		'apellido2' => 'Elizondo',
    		'nombre_c' => 'Perla Inés Velasco Elizondo',
    		'a_n' => 'PIVE',
    		'lic' => '',
    		'puesto' => 'Subsecretaria de Planeación y Evaluación',
    		'direccion' => ' Subsecretaria de Planeación y Evaluación ',
    		'a_d' => 'SPE',
    		'correo' => 'pvelasco@seduzac.gob.mx',
    		'ext' => '5100',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Agustin ',
    		'apellido1' => 'Vital',
    		'apellido2' => 'Chavez',
    		'nombre_c' => 'Agustin  Vital Chavez',
    		'a_n' => 'AVC',
    		'lic' => '',
    		'puesto' => 'Secretario Tecnico',
    		'direccion' => ' Secretaria Tecnica ',
    		'a_d' => '',
    		'correo' => 'stplanyeval@seduzac.gob.mx',
    		'ext' => '5110',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Sergio',
    		'apellido1' => 'Salazar',
    		'apellido2' => 'Cortez',
    		'nombre_c' => 'Sergio Salazar Cortez',
    		'a_n' => 'SSC',
    		'lic' => '',
    		'puesto' => 'Director de Innovación y Gestión Institucional',
    		'direccion' => ' Dirección de Innovación y Gestión Institucional ',
    		'a_d' => 'DIGI',
    		'correo' => 'innovacion@seduzac.com.mx',
    		'ext' => '5120',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ma. Guadalupe',
    		'apellido1' => 'Ramírez ',
    		'apellido2' => 'Muñoz',
    		'nombre_c' => 'Ma. Guadalupe Ramírez  Muñoz',
    		'a_n' => 'MGRM',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Mejora y Desarrollo',
    		'direccion' => ' Departamento de Mejora y Desarrollo ',
    		'a_d' => 'DMD',
    		'correo' => 'mejora.desarrollo@seduzac.gob.mx',
    		'ext' => '5120',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'J. Guadalupe',
    		'apellido1' => 'Del Real',
    		'apellido2' => 'Álvarez',
    		'nombre_c' => 'J. Guadalupe Del Real Álvarez',
    		'a_n' => 'JGDRÁ',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Estadística y Sistemas',
    		'direccion' => ' Departamento de Estadística y Sistemas ',
    		'a_d' => 'DES',
    		'correo' => 'estadistica.sistemas@seduzac.gob,mx',
    		'ext' => '5122',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Dulce Carolina',
    		'apellido1' => 'González',
    		'apellido2' => 'Lara',
    		'nombre_c' => 'Dulce Carolina González Lara',
    		'a_n' => 'DCGL',
    		'lic' => '',
    		'puesto' => 'Directora de Planeación',
    		'direccion' => ' Dirección de Planeación ',
    		'a_d' => 'DP',
    		'correo' => 'dgonzalez@seduzac,gob.mx',
    		'ext' => '5150',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Joel',
    		'apellido1' => 'Zamora',
    		'apellido2' => 'De la Torre',
    		'nombre_c' => 'Joel Zamora De la Torre',
    		'a_n' => 'JZDT',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Programación y Presupuesto',
    		'direccion' => ' Departamento de Programación y Presupuesto ',
    		'a_d' => 'DPP',
    		'correo' => 'presupuestal@seduzac.gob.mx',
    		'ext' => '5150',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ma. De Lourdes',
    		'apellido1' => 'Escareño',
    		'apellido2' => 'Acosta',
    		'nombre_c' => 'Ma. De Lourdes Escareño Acosta',
    		'a_n' => 'MDLEA',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Control Escolar',
    		'direccion' => ' Departamento de Control Escolar ',
    		'a_d' => 'DCE',
    		'correo' => 'regcaestudios@seduzac.gob.mx',
    		'ext' => '5130',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ramiro',
    		'apellido1' => 'Bonilla',
    		'apellido2' => 'Carrillo',
    		'nombre_c' => 'Ramiro Bonilla Carrillo',
    		'a_n' => 'RBC',
    		'lic' => '',
    		'puesto' => 'Director de Espacios Educativos',
    		'direccion' => ' Dirección de Espacios Educativos ',
    		'a_d' => 'DEE',
    		'correo' => 'direspedo@seduzac.gob.mx',
    		'ext' => '5153',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Armando',
    		'apellido1' => 'López',
    		'apellido2' => 'Martínez',
    		'nombre_c' => 'Armando López Martínez',
    		'a_n' => 'ALM',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Infraestructura',
    		'direccion' => ' Departamento de Infraestructura ',
    		'a_d' => 'DI',
    		'correo' => 'infraestructura@seduzac.gob.mx',
    		'ext' => '5153',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Micaela',
    		'apellido1' => 'Álvarez',
    		'apellido2' => 'Álvarez',
    		'nombre_c' => 'Micaela Álvarez Álvarez',
    		'a_n' => 'MÁÁ',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Fortalecimiento',
    		'direccion' => ' Departamento de Fortalecimiento ',
    		'a_d' => 'DF ',
    		'correo' => 'mobiliarioyequipo@seduzac.gob.mx',
    		'ext' => '5153',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Antonio ',
    		'apellido1' => 'Vázquez ',
    		'apellido2' => 'Rodríguez',
    		'nombre_c' => 'Antonio  Vázquez  Rodríguez',
    		'a_n' => 'AVR',
    		'lic' => 'L.C',
    		'puesto' => 'Subsecretario Administrativo',
    		'direccion' => ' Subsecretaria Administrativa ',
    		'a_d' => 'SA',
    		'correo' => 'avazquez@seduzac.gob.mx',
    		'ext' => '5600',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'José Edgardo ',
    		'apellido1' => 'Ochoa',
    		'apellido2' => 'Elias',
    		'nombre_c' => 'José Edgardo  Ochoa Elias',
    		'a_n' => 'JEOE',
    		'lic' => '',
    		'puesto' => 'Secretario Técnico',
    		'direccion' => ' Secretaria Tecnica ',
    		'a_d' => '',
    		'correo' => 'eochoa@seduzac.gob.mx',
    		'ext' => '5602',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ana Lilia',
    		'apellido1' => 'Rojas',
    		'apellido2' => 'Vásquez',
    		'nombre_c' => 'Ana Lilia Rojas Vásquez',
    		'a_n' => 'ALRV',
    		'lic' => '',
    		'puesto' => 'Directora de Capital Humano',
    		'direccion' => ' Dirección de Capital Humano ',
    		'a_d' => 'DCH',
    		'correo' => 'jefaturadepersonal@seduzac.gob.mx',
    		'ext' => '5610',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Susana ',
    		'apellido1' => 'Robles ',
    		'apellido2' => 'Berumen',
    		'nombre_c' => 'Susana  Robles  Berumen',
    		'a_n' => 'SRB',
    		'lic' => '',
    		'puesto' => 'Encargada del Departamento de Plazas Federalizadas',
    		'direccion' => ' Departamento de Plazas Federalizadas ',
    		'a_d' => 'DPF',
    		'correo' => 'roblesberumen@gmail.com',
    		'ext' => '5617',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Magdalena de Jesús',
    		'apellido1' => 'Luévano',
    		'apellido2' => 'Galindo',
    		'nombre_c' => 'Magdalena de Jesús Luévano Galindo',
    		'a_n' => 'MJLG',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Plazas Estatales',
    		'direccion' => ' Departamento de Plazas Estatales ',
    		'a_d' => 'DPE',
    		'correo' => 'maggy_seduzac@yahoo.com.mx',
    		'ext' => '5620',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan Manuel ',
    		'apellido1' => 'Ramirez ',
    		'apellido2' => 'Aviña',
    		'nombre_c' => 'Juan Manuel  Ramirez  Aviña',
    		'a_n' => 'JMRA',
    		'lic' => '',
    		'puesto' => 'Encargado del Departamento de Pagos',
    		'direccion' => ' Departamento de Pagos ',
    		'a_d' => 'DP',
    		'correo' => 'pagos.sec@hotmail.com',
    		'ext' => '5683',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan Diego',
    		'apellido1' => 'Gonzalez',
    		'apellido2' => 'Carlos',
    		'nombre_c' => 'Juan Diego Gonzalez Carlos',
    		'a_n' => 'JDGC',
    		'lic' => 'Ing',
    		'puesto' => 'Jefe del Departamento de Nómina',
    		'direccion' => ' Departamento de Nómina ',
    		'a_d' => 'DN',
    		'correo' => 'nomina@seduzac.gob.mx',
    		'ext' => '5700',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Edgar',
    		'apellido1' => 'Fernández',
    		'apellido2' => 'Mejía',
    		'nombre_c' => 'Edgar Fernández Mejía',
    		'a_n' => 'EFM',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Desarrollo Profesional Administrativo',
    		'direccion' => ' Departamento de Desarrollo Profesional Administrativo ',
    		'a_d' => 'DDPA',
    		'correo' => 'jefaturadepersonal@seduzac.gob.mx',
    		'ext' => '5610',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Zoila Marisol',
    		'apellido1' => 'Sanchez',
    		'apellido2' => 'Flores',
    		'nombre_c' => 'Zoila Marisol Sanchez Flores',
    		'a_n' => 'ZMSF',
    		'lic' => '',
    		'puesto' => 'Directora de Recursos Financieros ',
    		'direccion' => ' Dirección de Recursos Financieros  ',
    		'a_d' => 'DRF',
    		'correo' => 'financieros@seduzac.gob.mx',
    		'ext' => '5663',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Vacante',
    		'apellido1' => 'vacante',
    		'apellido2' => 'vacante',
    		'nombre_c' => 'Vacante vacante vacante',
    		'a_n' => 'V',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Presupuesto',
    		'direccion' => ' Departamento de Presupuesto ',
    		'a_d' => 'DP',
    		'correo' => 'presupuesto@seduzac.gob.mx',
    		'ext' => '5664',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Sofia Lorena',
    		'apellido1' => 'Flores',
    		'apellido2' => 'Lerma',
    		'nombre_c' => 'Sofia Lorena Flores Lerma',
    		'a_n' => 'SLFL',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Contabilidad',
    		'direccion' => ' Departamento de Contabilidad ',
    		'a_d' => 'DC',
    		'correo' => 'contabilidad@seduzac.gob.mx',
    		'ext' => '5673',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Laura del Rosario',
    		'apellido1' => 'Camporredondo',
    		'apellido2' => 'Reyes',
    		'nombre_c' => 'Laura del Rosario Camporredondo Reyes',
    		'a_n' => 'LRCR',
    		'lic' => '',
    		'puesto' => 'Jefa del Departamento de Tesorería',
    		'direccion' => ' Departamento de Tesorería ',
    		'a_d' => 'DT ',
    		'correo' => 'tesoreria@seduzac.gob.mx',
    		'ext' => '5676',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Luis Manuel',
    		'apellido1' => 'Cid',
    		'apellido2' => 'Trejo',
    		'nombre_c' => 'Luis Manuel Cid Trejo',
    		'a_n' => 'LMCT',
    		'lic' => '',
    		'puesto' => 'Jefe del Departamento de Simplificación Administrativa',
    		'direccion' => ' Departamento de Simplificación Administrativa ',
    		'a_d' => 'DSA',
    		'correo' => 'fiscalización@seduzac.gob.mx',
    		'ext' => '5668',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'María del Rosario',
    		'apellido1' => 'Zamora',
    		'apellido2' => 'López',
    		'nombre_c' => 'María del Rosario Zamora López',
    		'a_n' => 'MRZL',
    		'lic' => '',
    		'puesto' => 'Directora de Recursos Materiales',
    		'direccion' => ' Dirección de Recursos Materiales ',
    		'a_d' => 'DRM',
    		'correo' => 'rzamora@seduzac.gob.mx',
    		'ext' => '5630',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Ana Lilia',
    		'apellido1' => 'Torres ',
    		'apellido2' => 'Sosa',
    		'nombre_c' => 'Ana Lilia Torres  Sosa',
    		'a_n' => 'ALTS',
    		'lic' => '',
    		'puesto' => 'Encargada del Departamento de Almacén e Inventarios',
    		'direccion' => ' Departamento de Almacén e Inventarios ',
    		'a_d' => 'DAI',
    		'correo' => 'almacen@seduzac.gob.mx',
    		'ext' => '5652',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Juan Manuel ',
    		'apellido1' => 'Carrillo',
    		'apellido2' => 'Delgado',
    		'nombre_c' => 'Juan Manuel  Carrillo Delgado',
    		'a_n' => 'JMCD',
    		'lic' => '',
    		'puesto' => 'Encargado del Departamento de Mantenimiento',
    		'direccion' => ' Departamento de Mantenimiento ',
    		'a_d' => 'DM ',
    		'correo' => 'mantenimiento@seduzac.gob.mx',
    		'ext' => '5635',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Alan Arturo',
    		'apellido1' => 'Aguilar',
    		'apellido2' => 'Campos',
    		'nombre_c' => 'Alan Arturo Aguilar Campos',
    		'a_n' => 'AAAC',
    		'lic' => '',
    		'puesto' => 'Encargado del Departamento de Servicios y Soporte Técnico',
    		'direccion' => ' Departamento de Servicios y Soporte Técnico ',
    		'a_d' => 'DSST',
    		'correo' => 'servicios@seduzac.gob.mx',
    		'ext' => '5649',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);
    	DB::table('DirectorioExterno')->insert([
    		'nombre' => 'Yolanda ',
    		'apellido1' => 'Medina',
    		'apellido2' => 'De la Isla',
    		'nombre_c' => 'Yolanda  Medina De la Isla',
    		'a_n' => 'YMDI',
    		'lic' => '',
    		'puesto' => 'Encargada del Departamento de Compras y Adquisiciones',
    		'direccion' => ' Departamento de Compras y Adquisiciones ',
    		'a_d' => 'DCA',
    		'correo' => 'yolanda.medina@seduzac.gob.mx',
    		'ext' => '5640',
    		'captura' => 'ADMINISTRADOR',
    		'estado' => 'ACTIVO',		
    		'created_at' => '0000-00-00 00:00:00',
    		'updated_at' => '0000-00-00 00:00:00'
    		]);

        //
    }
}
